name: build-windows-exe
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Tidy
        run: go mod tidy
      - name: Build (GUI)
        run: go build -ldflags "-s -w -H=windowsgui" -o KadastrApp.exe kadastr_gui_fyne.go
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KadastrApp
          path: KadastrApp.exe
